version: '3.3'

networks:
  appnet:
    external: true

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - appnet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - appnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    ports:
      - 3000:8080
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - appnet